### ISSUE TITLE
 当@type不是排在最前面的时候，反序列化会丢失@type之前的字段

### ISSUE THREAD

**Issue by magicdoom** [alibaba/fastjson#291] opened 2015-01-31 10:05 UTC
当@type不是排在最前面的时候，反序列化会丢失@type之前的字段。(主要发生在第二层以上，在最外层则不影响)
因为底层存储的原因，@type的顺序跟序列化的时候不一样。
这个问题是否可以有方法解决

**Comment by 089apps** [comment] 2015-10-18 19:06
Same problem here. 
I  have following JSON Array(!):

[{"foo1": "value1", "@type": "com.foo.FooModel", "foo2": "value2"}, 
{"foofoo1": "value1", "@type": "com.foo.FooFooModel", "foofoo2": "value2"}, 
{"foofoofoo1": "value1", "@type": "com.foo.FooFooFooModel", "foofoofoo2": "value2"}]

Only the values of foo2, foofoo2 and foofoofoo2 were parsed successfully,
while the values of foo1, foofoo1 and foofoofoo1 are ignored.

I guess it is a bug at JavaBeanDeserializer, lines 290ff 
probably the Lexer(JSONScanner) position needs to be set at the first char of the current JSON item before going into following lines:

Class<?> userType = TypeUtils.loadClass(typeName);
ObjectDeserializer deserizer = parser.getConfig().getDeserializer(userType);
return (T) deserizer.deserialze(parser, userType, fieldName);

**Comment by 089apps** [comment] 2015-10-18 19:25
Duplicate of https://github.com/alibaba/fastjson/issues/406

**Comment by wenshao** [comment] 2016-04-13 09:45
bug fixed. included in 1.2.9 & 1.1.49.android

**Closed by wenshao** 2016-04-13 09:45 UTC

**Comment by MindSelf** [comment] 2021-05-10 09:39
> bug fixed. included in 1.2.9 & 1.1.49.android

这个bug在1.1.71版本还没得到解决
